CREATE TABLE IF NOT EXISTS "searched_car_listings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "searched_car_listings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"saved_search_id" integer NOT NULL,
	"listing_hash" varchar(255) NOT NULL,
	"listing_id" varchar(255),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
ALTER TABLE "saved_search" ADD COLUMN "last_run" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "saved_search" ADD COLUMN "next_page_data" jsonb;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "searched_car_listings" ADD CONSTRAINT "searched_car_listings_saved_search_id_saved_search_id_fk" FOREIGN KEY ("saved_search_id") REFERENCES "public"."saved_search"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "searched_car_listings_saved_search_id_idx" ON "searched_car_listings" USING btree ("saved_search_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "searched_car_listings_unique_hash" ON "searched_car_listings" USING btree ("saved_search_id","listing_hash");